/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package program;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import static java.lang.Thread.yield;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
/**
 *
 * @author SzabóRoland(SZF_2023
 */
public class MainGUI extends javax.swing.JFrame implements EI.charachterListener{

    /**
     * Creates new form MainGUI
     */
    int ehe = 0;
    public MainGUI() {
        initComponents();
        Pr_eletero.setMaximum(Idoregesz.getMaxEletero());
        Idoregesz.addListener(this);
        Idoregesz.Restart(true);
        this.getContentPane().setBackground( Color.ORANGE );
        La_output.setOpaque(true);
        La_output.setBackground(Color.CYAN);
    }
    
    @Override
    public void charachterUpdate(){
        Pr_eletero.setValue(Idoregesz.getEletero());
        La_eletero.setText(String.valueOf(Idoregesz.getEletero()));
        La_hiba.setText(getListToTextForJLabel(new String[]{""}));
        La_talal.setText(getListToTextForJLabel(new String[]{""}));
        La_inventory.setText(getListToTextForJLabel(new String[]{""}));
        
        //Kép
        Path currentRelativePath = Paths.get("");
        String s = currentRelativePath.toAbsolutePath().toString();
        //System.out.println(s);
        File f = new File(s + "\\" + Idoregesz.getKep());
        System.out.println(f.getPath());
        if(f.exists()){
            
            
            try {
                BufferedImage wPic = ImageIO.read(f);
                System.out.println("Geci.");
                Image img = wPic.getScaledInstance(309, 215, Image.SCALE_DEFAULT);
                ImageIcon ic = new ImageIcon(img);
                La_kep.setIcon(ic);
               
            } catch (Exception e) {
                System.out.println("Kurva anyád!");
            }
        }
        
        La_output.setText("<html><p style=\"padding: 3px 1px 3px 5px;\">"+Idoregesz.getLeiras()+"</p></html>");
        System.out.println(String.format("%d. Pisztácia elfogyott, vanillia nem is volt.", ehe));
        ehe++;
    }
    
    private void Command(){
        if(Idoregesz.Command(Tf_input.getText().split(" "))){
           //La_hiba
           Tf_input.setText("");
        }
        else{
            //La_hiba.setText("<html>Hiba: Ez a parancs nem elfogadott!</html>");
        }
    }

    private String getListToTextForJLabel(String[] l){
        String s = "<html>";
        for (String item : l){
            s += item + "<br>";
        } s+="</html>";
        return s;
    }
    private String getListToText(String[] l){
        String s = "";
        for (String item : l){
            s += item + "\n";
        }
       return s;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pa_kep = new javax.swing.JPanel();
        La_kep = new javax.swing.JLabel();
        La_output = new javax.swing.JLabel();
        La_hiba = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Pr_eletero = new javax.swing.JProgressBar();
        La_eletero = new javax.swing.JLabel();
        Bt_send = new javax.swing.JButton();
        Tf_input = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        La_inventory = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        La_talal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 0));
        setResizable(false);

        Pa_kep.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Pa_kep.setMaximumSize(new java.awt.Dimension(309, 215));
        Pa_kep.setMinimumSize(new java.awt.Dimension(309, 215));
        Pa_kep.setPreferredSize(new java.awt.Dimension(309, 215));

        La_kep.setMaximumSize(new java.awt.Dimension(309, 215));
        La_kep.setMinimumSize(new java.awt.Dimension(309, 215));
        La_kep.setPreferredSize(new java.awt.Dimension(309, 215));

        javax.swing.GroupLayout Pa_kepLayout = new javax.swing.GroupLayout(Pa_kep);
        Pa_kep.setLayout(Pa_kepLayout);
        Pa_kepLayout.setHorizontalGroup(
            Pa_kepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(La_kep, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        Pa_kepLayout.setVerticalGroup(
            Pa_kepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pa_kepLayout.createSequentialGroup()
                .addComponent(La_kep, javax.swing.GroupLayout.PREFERRED_SIZE, 209, Short.MAX_VALUE)
                .addContainerGap())
        );

        La_output.setBackground(new java.awt.Color(153, 255, 255));
        La_output.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        La_output.setText("<html>A főnév és helyszín szavak a leírásokban lesznek megtalálhatóak, arra kell figyelni, ha egy adott helyszínen van felvehető tárgy, akkor felvétele után az nem lesz ott, csak a felszereléseink között. Kivéve az étel, az mindig ott marad! Amikor megfelelő helyen használtuk a tárgyat, akkor az a felszerelések közül eltűnhet, de pl. egy kulcs vissza is kerülhet a felszerelések közé.</html>");
        La_output.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        La_output.setMaximumSize(new java.awt.Dimension(200, 160));
        La_output.setOpaque(true);

        La_hiba.setBackground(new java.awt.Color(204, 204, 204));
        La_hiba.setForeground(new java.awt.Color(255, 51, 51));
        La_hiba.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        La_hiba.setText("Hiba");
        La_hiba.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel3.setText("Hibaüzenetek:");

        Pr_eletero.setBackground(new java.awt.Color(51, 255, 51));
        Pr_eletero.setMaximum(10);
        Pr_eletero.setValue(3);

        La_eletero.setText("0");

        Bt_send.setText("küldés");
        Bt_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bt_sendActionPerformed(evt);
            }
        });

        Tf_input.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Tf_inputKeyPressed(evt);
            }
        });

        jLabel1.setText("Életerő:");

        jLabel2.setText("Eszköztár:");

        La_inventory.setText("Minta");
        La_inventory.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel4.setText("Itt van:");

        La_talal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        La_talal.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        La_talal.setAutoscrolls(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(106, 106, 106)
                        .addComponent(Tf_input, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(La_eletero, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Pr_eletero, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(La_inventory, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(La_output, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(Pa_kep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(Bt_send)
                    .addComponent(La_hiba, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                    .addComponent(La_talal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(La_inventory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(La_eletero)
                                        .addComponent(jLabel1))
                                    .addComponent(Pr_eletero, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8))
                            .addComponent(Pa_kep, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(La_output, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(La_hiba, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(La_talal, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Bt_send)
                    .addComponent(Tf_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Bt_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bt_sendActionPerformed
        this.Command();
    }//GEN-LAST:event_Bt_sendActionPerformed

    private void Tf_inputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Tf_inputKeyPressed
        if('\n' == evt.getKeyChar()){
            this.Command();
        }
    }//GEN-LAST:event_Tf_inputKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bt_send;
    private javax.swing.JLabel La_eletero;
    private javax.swing.JLabel La_hiba;
    private javax.swing.JLabel La_inventory;
    private javax.swing.JLabel La_kep;
    private javax.swing.JLabel La_output;
    private javax.swing.JLabel La_talal;
    private javax.swing.JPanel Pa_kep;
    private javax.swing.JProgressBar Pr_eletero;
    private javax.swing.JTextField Tf_input;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
